package com.example.restapp.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Author")
public class Author {

    private String authorId;
    private String firstname;
    private String lastname;
    private String description;
    private String image;
    private float rating;
    private int ratingCount;
    private float displayRating;


    public Author() {
    }

    public Author(String firstname, String lastname, String description, String image, float rating, int ratingCount,float displayRating) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.description = description;
        this.image = image;
        this.rating = rating;
        this.ratingCount = ratingCount;
        this.displayRating = displayRating;
    }

    @DynamoDBHashKey(attributeName = "authorId")
    @DynamoDBAutoGeneratedKey
    public String getAuthorId() {
        return authorId;
    }

    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }

    @DynamoDBAttribute(attributeName = "FirstName")
    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @DynamoDBAttribute(attributeName = "LastName")
    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @DynamoDBAttribute(attributeName = "Description")
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute(attributeName = "image")
    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @DynamoDBAttribute(attributeName = "Rating")
    public float getRating() {
        return rating;
    }

    public void setRating(float rating) {
        this.rating = rating;
    }

    @DynamoDBAttribute(attributeName = "RatingCount")
    public int getRatingCount() {
        return ratingCount;
    }

    public void setRatingCount(int ratingCount) {
        this.ratingCount = ratingCount;
    }

    @DynamoDBAttribute(attributeName = "DisplayRating")
    public float getDisplayRating() {
        return displayRating;
    }

    public void setDisplayRating(float displayRating) {
        this.displayRating = displayRating;
    }
}
